spring:
  profiles:
    active: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ita?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
#    username: root
#    password: 123456

server:
  port: 8888

logging:
  config: classpath:logback-spring.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true

---

###########################################
# 开发环境
###########################################

spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://157.245.210.150:3328/ita?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: Nzk3YjIxZTFmMzQ1YzQxYTg2MzNhM2Q1MWU3MzZkODU=
      driver-class-name: com.mysql.jdbc.Driver

---
###########################################
# 测试环境
###########################################

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/ita?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
